/**
 * Single source of truth for "does this star need translation?"
 *
 * R50 root cause (5th iteration of the "翻译 N 个 stuck" bug): the UI
 * counter (`untranslatedCount` useMemo) and the orchestrator skip-loop
 * each had their own ad-hoc judgment, and the UI render's tag-display
 * had a THIRD judgment (fallback to `star.aiTags` when i18n cache empty).
 * The three diverged in one specific case: when `star.aiTags` was
 * GENERATED in the target locale's script (user ran auto-tag on a
 * Chinese-model provider like DashScope/SiliconFlow, which inherits the
 * model's default output language → aiTags arrive as ["金融分析", "AI交易"]).
 * Concretely:
 *   - UI render: `localizedRaw || star.aiTags` → shows Chinese ✅
 *   - UI count: `!aiTagsI18n[locale]` → counts as "needs translation" ❌
 *   - orchestrator: `tagsDone` only true when cache populated → enters worker
 *
 * Result: user clicks "翻译 9 个", LLM is asked to translate Chinese into
 * Chinese, may return empty/refusal/same → tagsFailed++ or noisy re-write
 * → count unchanged → user reports "click does nothing 5 times in a row".
 *
 * This module fixes it by giving all three surfaces a single import. The
 * key insight: if the source content is ALREADY in the target locale's
 * script, treat it as translated (and let the orchestrator backfill the
 * cache for free, no LLM call).
 */
import type { StarredRepo } from '../schema.js';

/**
 * Locale → regex matching at least one character from that locale's
 * defining script. Used to detect "this string is probably already in
 * the target language" without hitting a model.
 *
 * Latin-script locales (en, de, fr, es, pt-BR) are intentionally absent:
 * we can't distinguish "English aiTags" from "French aiTags" by Unicode
 * range alone, so they fall back to strict cache-only logic. That's
 * acceptable because the original bug was reported in zh-CN; CJK + Cyrillic
 * + Korean + Hangul scripts are unambiguous markers.
 *
 * If a future locale needs to be added, the regex should match at LEAST
 * one codepoint that's exclusive to that locale's script family.
 */
const SCRIPT_RANGES: Record<string, RegExp> = {
  'zh-CN': /[一-鿿]/,
  'zh-TW': /[一-鿿]/,
  // Japanese: hiragana, katakana, OR CJK (kanji shared with Chinese; matched
  // generously — false positives just mean "skip the translate call" which
  // is safe for a JP user looking at JP content).
  ja: /[぀-ゟ゠-ヿ一-鿿]/,
  ko: /[가-힯]/, // Hangul syllables
  ru: /[Ѐ-ӿ]/, // Cyrillic
  vi: /[À-ỹ]/, // Vietnamese latin with diacritics (broad block)
};

/**
 * True iff the given source text is already plausibly in the target locale.
 * Locale-agnostic (Latin-script locales) → returns false so cache logic
 * takes over.
 *
 * `null` / empty string → returns false (nothing to test); caller handles
 * the "no content to translate" case separately.
 */
export function isLikelyInLocale(text: string | null | undefined, locale: string): boolean {
  if (!text || text.length === 0) return false;
  const re = SCRIPT_RANGES[locale];
  if (!re) return false; // unknown locale or Latin-script — don't guess
  return re.test(text);
}

/**
 * Does this star's aiTags need a (re-)translation pass for the target locale?
 *
 * False when:
 *   - locale === 'en' (en is the source language; never translate to en)
 *   - aiTags is empty (nothing to translate)
 *   - aiTagsI18n[locale] is a non-empty string (already cached)
 *   - aiTags are already in the target locale's script (zero-cost backfill
 *     candidate — orchestrator can write `star.aiTags.join(', ')` directly
 *     to the cache without an LLM round trip)
 *
 * True otherwise — the orchestrator should run the tags chat for this star.
 */
export function tagsNeedTranslation(star: StarredRepo, locale: string): boolean {
  if (locale === 'en') return false;
  if (star.aiTags.length === 0) return false;
  const cached = star.aiTagsI18n?.[locale];
  if (typeof cached === 'string' && cached.length > 0) return false;
  // R50 key insight: aiTags generated by a same-locale model are already
  // translated — flagging them as "needs translation" causes the 5th-iteration
  // user-visible bug. Cheap script-range check eliminates the false positive.
  if (isLikelyInLocale(star.aiTags.join(' '), locale)) return false;
  return true;
}

/**
 * Same logic for description. Mirror semantics so the UI counter, the
 * orchestrator skip-loop, and the manage page all use one truth.
 *
 * Description is far less likely to be "already in target locale" because
 * GitHub repo descriptions are typically English, but the heuristic is
 * applied symmetrically for parity (and to handle repos whose owner wrote
 * the description in Chinese / Japanese / etc.).
 */
export function descriptionNeedsTranslation(star: StarredRepo, locale: string): boolean {
  if (locale === 'en') return false;
  if (!star.description || star.description.trim().length === 0) return false;
  const cached = star.descriptionI18n?.[locale];
  if (typeof cached === 'string' && cached.length > 0) return false;
  if (isLikelyInLocale(star.description, locale)) return false;
  return true;
}

/**
 * Top-level: should this star appear in the "translate N stars" button count?
 * = description needs OR tags need.
 */
export function starNeedsTranslation(star: StarredRepo, locale: string): boolean {
  return (
    descriptionNeedsTranslation(star, locale) || tagsNeedTranslation(star, locale)
  );
}
