/**
 * Obsidian plugin build pipeline.
 *
 * Bundles `src/main.ts` -> `main.js` in CommonJS form (required by Obsidian's
 * plugin loader). Obsidian's API is provided externally — we don't bundle it.
 */
import esbuild from 'esbuild';
import process from 'node:process';
import builtins from 'builtin-modules';

const isProd = process.argv[2] === 'production';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/
`;

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2022',
  logLevel: 'info',
  sourcemap: isProd ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: isProd,
});

if (isProd) {
  await ctx.rebuild();
  process.exit(0);
} else {
  await ctx.watch();
  console.info('[starkit:obsidian] watching for changes...');
}
